steps:
  - label: ":python:"
    agents:
      queue: default
    commands:
      - mkdir dist
      - docker build -v $$PWD/dist:/app/dist .
    artifact_paths:
      - dist/minecraft_building_assistance_game-*.whl
