
def init(
    address=None,
    *,
    num_cpus=None,
    num_gpus=None,
    resources=None,
    object_store_memory=None,
    local_mode=False,
    ignore_reinit_error=False,
    include_dashboard=None,
    dashboard_host=...,
    dashboard_port=None,
    job_config=None,
    configure_logging=True,
    logging_level=...,
    logging_format=...,
    log_to_driver=True,
    # The following are unstable parameters and their use is discouraged.
    _enable_object_reconstruction=False,
    _redis_max_memory=None,
    _plasma_directory=None,
    _node_ip_address=...,
    _driver_object_store_memory=None,
    _memory=None,
    _redis_password=...,
    _temp_dir=None,
    _lru_evict=False,
    _metrics_export_port=None,
    _system_config=None,
): ...
